#Multi-Step docker build file
#To tag any phase in dockerfile, use as to name the phase
FROM node:alpine as builder

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

RUN npm run build

FROM nginx
COPY --from=builder  /app/build /usr/share/nginx/html