export const SIGN_IN = "SIGN_IN";
export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const FETCH_RESTAURANTS = "FETCH_RESTAURANTS";
export const FETCH_RESTAURANT_DETAILS = "FETCH_RESTAURANT_DETAILS";
export const UPDATE_RESTAURANT_REVIEW = "UPDATE_RESTAURANT_REVIEW";
export const SEARCH_RESTAURANTS = "SEARCH_RESTAURANTS";